package com.bear.common.model;

import com.bear.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public User(){}
	public User(String name, int age){
		this.setName(name);
		this.setAge(age);
	}
}
